# Generated by Django 4.0.4 on 2022-04-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='neighborhood',
            new_name='neighbourhood',
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Business Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Business Email Address')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhood', verbose_name='NeighbourHood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.profile', verbose_name='Business Owner')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
    ]
